### ISSUE TITLE
remove hardcoded #'ExecutorInfo'{source = "riak"}, it assumes framework name = "riak"

### ISSUE THREAD

**Issue by mokele** [basho-labs/riak-mesos-executor#19]
Been as though the framework name is configurable in RMF I was confused to find out the source element of `ExecutorInfo` gets passed through as the framework name causing a crash in `rme_rnp:setup/1 line 61` where `"riak"` is hardcoded

see https://github.com/basho-labs/riak-mesos-executor/blob/master/src/rme_rnp.erl#L59

This is relevant to us in a development setup where each user of a cluster will be administering their own riak scheduler instance with differing names.

**Comment by mokele** [comment]
simply commenting out the `ExecutorInfo` pattern patch fixes the problem. I can submit a pull-request, but hadn't tested it before writing this issue up earlier

**Comment by sanmiguel** [comment]
Thanks for reporting this @mokele - I'm just looking info whether we need to make any efforts to validate that `#'ExecutorInfo'.source` data against anything but I don't see anything so we can just remove it.

If you've got the patch ready, please feel free to submit as a PR, otherwise I can take care of it. LMK either way!

Thanks again!

**Comment by mokele** [comment]
I don't have a patch handy and isn't really worth forking and putting in a pull-request tbh, so you go ahead

Cheers!

**Comment by sanmiguel** [comment]
@mokele see linked PR (#20) for the fix.

NB: if you're running multiple RMF instances in a single cluster, you may hit a problem I just discovered with the scheduler component. I've raised the corresponding issue (basho-labs/riak-mesos-scheduler#60) and will investigate from there.

**Comment by mokele** [comment]
ah yeah, thanks for the warning. I will have found that one out first thing tomorrow morning when I tried it out. Thanks for the heads-up
